'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.3634
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace CEF.WebUI

    '''<summary>
    '''Clase busMetodizado.
    '''</summary>
    '''<remarks>
    '''Clase generada automáticamente.
    '''</remarks>
    Partial Public Class busMetodizado

        '''<summary>
        '''Control Form2.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Form2 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''Control hidMntAccion.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents hidMntAccion As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''Control hidCodMetodizado.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents hidCodMetodizado As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''Control Image4.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image4 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control Image6.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image6 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control Image5.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image5 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control imgCerrar.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents imgCerrar As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''Control Image7.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image7 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control vsmMnt.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents vsmMnt As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''Control pnlCabMetodizado.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents pnlCabMetodizado As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''Control btnBuscar.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents btnBuscar As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''Control btnInicializar.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents btnInicializar As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''Control ltlPerfilUsuarioLogin.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents ltlPerfilUsuarioLogin As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''Control txtNomUsuarioLogin.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents txtNomUsuarioLogin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Control txtCUCliente.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents txtCUCliente As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Control lblSegmento.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents lblSegmento As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Control ddlSegmento.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents ddlSegmento As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''Control dropTipoDocumento.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents dropTipoDocumento As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''Control txtRUC.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents txtRUC As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Control txtRazonSocial.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents txtRazonSocial As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Control txtCodCIIU.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents txtCodCIIU As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Control txtNombreCIIU.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents txtNombreCIIU As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Control imgBusCIIU.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents imgBusCIIU As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control txtCodGrupoEconomico.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents txtCodGrupoEconomico As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Control txtNombreGrupoEconomico.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents txtNombreGrupoEconomico As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Control imgBusGrupoEconomico.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents imgBusGrupoEconomico As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control dropAnalista.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents dropAnalista As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''Control dropEjecutivo.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents dropEjecutivo As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''Control dropEstado.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents dropEstado As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''Control txtFecInicio.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents txtFecInicio As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Control imgFecInicio.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents imgFecInicio As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control txtFecFin.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents txtFecFin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Control imgFecFin.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents imgFecFin As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control lblNumReg.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents lblNumReg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Control imgNuevo.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents imgNuevo As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''Control lnkNuevo.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents lnkNuevo As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''Control imgImprimir.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents imgImprimir As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control lnkImprimir.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents lnkImprimir As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''Control dgrdMnt.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents dgrdMnt As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''Control Image8.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image8 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control Image9.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image9 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control Image12.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image12 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control Image10.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image10 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control Image13.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image13 As Global.System.Web.UI.WebControls.Image
    End Class
End Namespace
