'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8793
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace CEF.WebUI

    '''<summary>
    '''busSeleccionarPeriodoProyeccion class.
    '''</summary>
    '''<remarks>
    '''Auto-generated class.
    '''</remarks>
    Partial Public Class busSeleccionarPeriodoProyeccion

        '''<summary>
        '''Form2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Form2 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''hidMntAccion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidMntAccion As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hidCodMetodizado control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidCodMetodizado As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hidRazonSocial control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidRazonSocial As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''Image4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Image4 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Image6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Image6 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Image5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Image5 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''imgCerrar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgCerrar As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Image7 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Image7 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''vsmMnt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vsmMnt As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''pnlCabMetodizado control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlCabMetodizado As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtRazonSocial control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRazonSocial As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''hidConfirmacion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidConfirmacion As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''BtnAccionActualizarGrilla control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BtnAccionActualizarGrilla As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''lblNumReg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNumReg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ibtnNuevo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ibtnNuevo As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lnkNuevo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkNuevo As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''dgrdMnt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgrdMnt As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''Image8 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Image8 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Image9 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Image9 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Image12 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Image12 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Image10 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Image10 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Image13 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Image13 As Global.System.Web.UI.WebControls.Image
    End Class
End Namespace
