'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.3634
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace CEF.WebUI

    '''<summary>
    '''Clase consDescargaData.
    '''</summary>
    '''<remarks>
    '''Clase generada automáticamente.
    '''</remarks>
    Partial Public Class consDescargaData

        '''<summary>
        '''Control Form1.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''Control hidMntAccion.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents hidMntAccion As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''Control hidCodMetodizado.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents hidCodMetodizado As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''Control Image4.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image4 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control Image6.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image6 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control Image5.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image5 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control imgCerrar.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents imgCerrar As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''Control UpdatePanel1.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents UpdatePanel1 As Global.Anthem.Panel

        '''<summary>
        '''Control Image7.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image7 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control dropMoneda.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents dropMoneda As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''Control ddlEstado.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents ddlEstado As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''Control txtFecPeriodo.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents txtFecPeriodo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Control imgFecPeriodo.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents imgFecPeriodo As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control vreqFecPeriodo.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents vreqFecPeriodo As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''Control pnlCabMetodizado.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents pnlCabMetodizado As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''Control btnBuscar.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents btnBuscar As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''Control btnInicializar.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents btnInicializar As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''Control Img1.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Img1 As Global.System.Web.UI.HtmlControls.HtmlImage

        '''<summary>
        '''Control tab1_1.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents tab1_1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''Control img_tab1_1.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents img_tab1_1 As Global.System.Web.UI.HtmlControls.HtmlImage

        '''<summary>
        '''Control tab1_2.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents tab1_2 As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''Control lnk_Validados.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents lnk_Validados As Global.Anthem.LinkButton

        '''<summary>
        '''Control tab1_3.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents tab1_3 As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''Control img_tab1_3.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents img_tab1_3 As Global.System.Web.UI.HtmlControls.HtmlImage

        '''<summary>
        '''Control hidPestaniaActual.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents hidPestaniaActual As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''Control lblNumReg.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents lblNumReg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Control imgExpExcel.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents imgExpExcel As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control lnkExpExecel.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents lnkExpExecel As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''Control tr_Validados.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents tr_Validados As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''Control dgrdMnt.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents dgrdMnt As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''Control Image8.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image8 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control Image9.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image9 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control Image12.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image12 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control Image10.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image10 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control Image13.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image13 As Global.System.Web.UI.WebControls.Image
    End Class
End Namespace
