'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.3634
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace CEF.WebUI

    '''<summary>
    '''Clase mntAuditor.
    '''</summary>
    '''<remarks>
    '''Clase generada automáticamente.
    '''</remarks>
    Partial Public Class mntAuditor

        '''<summary>
        '''Control Form1.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''Control hidAccion.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents hidAccion As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''Control Image4.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image4 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control Image6.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image6 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control Image5.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image5 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control imgCerrar.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents imgCerrar As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''Control Image7.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image7 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control vsmMnt.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents vsmMnt As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''Control lblNumReg.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents lblNumReg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Control imbNuevo.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents imbNuevo As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''Control lnkNuevo.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents lnkNuevo As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''Control imgImprimir.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents imgImprimir As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control lnkImprimir.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents lnkImprimir As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''Control dgrdMnt.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents dgrdMnt As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''Control Image8.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image8 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control Image9.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image9 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control Image12.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image12 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control Image10.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image10 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control Image13.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image13 As Global.System.Web.UI.WebControls.Image
    End Class
End Namespace
