'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.3634
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace CEF.WebUI

    '''<summary>
    '''Clase mntPeriodoNota.
    '''</summary>
    '''<remarks>
    '''Clase generada automáticamente.
    '''</remarks>
    Partial Public Class mntPeriodoNota

        '''<summary>
        '''Control Form1.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''Control Image4.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image4 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control Image6.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image6 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control Image5.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image5 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control Image7.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image7 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control vsmMnt.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents vsmMnt As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''Control txtRazonSocial.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents txtRazonSocial As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Control txtCuenta.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents txtCuenta As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Control txtCodMetodizado.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents txtCodMetodizado As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Control HID_RptaServer.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents HID_RptaServer As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''Control HID_EnviaDatos.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents HID_EnviaDatos As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''Control HID_CodMetodizado.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents HID_CodMetodizado As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''Control HID_CodPeriodoFiltrado.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents HID_CodPeriodoFiltrado As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''Control HID_CodCuenta.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents HID_CodCuenta As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''Control HID_CodClientID.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents HID_CodClientID As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''Control HID_Idtx.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents HID_Idtx As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''Control BtnAccionEnviarDatos.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents BtnAccionEnviarDatos As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''Control lblNumReg.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents lblNumReg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Control ibtnNuevo.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents ibtnNuevo As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''Control lnkNuevo.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents lnkNuevo As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''Control imgImprimir.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents imgImprimir As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control lnkImprimir.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents lnkImprimir As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''Control dgdPeriodoNota.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents dgdPeriodoNota As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''Control pnlCabMetodizado.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents pnlCabMetodizado As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''Control BtnAceptar.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents BtnAceptar As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''Control Image8.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image8 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control Image9.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image9 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control Image12.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image12 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control Image10.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image10 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control Image13.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Image13 As Global.System.Web.UI.WebControls.Image
    End Class
End Namespace
