'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace wsRCC
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="bpsWebServiceSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class bpsWebService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private Get_Sel_Cuest_SolicitudOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Get_InformacionExternaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Get_CodigoSBSOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Get_ListadoDeudaRCCOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Set_CalcularScoringOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Get_CuestionarioXmlOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Set_CuestionarioSolicitudOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Get_Lst_Sist_Model_Area_ValorOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Get_List_Cuest_SolicitudDetalleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Get_ComportamientoXmlOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Get_ComportamientoDetXmlOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Get_ConexionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Get_ConexionBPSOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Get_BPSConexionWSOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.My.MySettings.Default.CEF_DataAccess_wsRCC_bpsWebService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event Get_Sel_Cuest_SolicitudCompleted As Get_Sel_Cuest_SolicitudCompletedEventHandler
        
        '''<remarks/>
        Public Event Get_InformacionExternaCompleted As Get_InformacionExternaCompletedEventHandler
        
        '''<remarks/>
        Public Event Get_CodigoSBSCompleted As Get_CodigoSBSCompletedEventHandler
        
        '''<remarks/>
        Public Event Get_ListadoDeudaRCCCompleted As Get_ListadoDeudaRCCCompletedEventHandler
        
        '''<remarks/>
        Public Event Set_CalcularScoringCompleted As Set_CalcularScoringCompletedEventHandler
        
        '''<remarks/>
        Public Event Get_CuestionarioXmlCompleted As Get_CuestionarioXmlCompletedEventHandler
        
        '''<remarks/>
        Public Event Set_CuestionarioSolicitudCompleted As Set_CuestionarioSolicitudCompletedEventHandler
        
        '''<remarks/>
        Public Event Get_Lst_Sist_Model_Area_ValorCompleted As Get_Lst_Sist_Model_Area_ValorCompletedEventHandler
        
        '''<remarks/>
        Public Event Get_List_Cuest_SolicitudDetalleCompleted As Get_List_Cuest_SolicitudDetalleCompletedEventHandler
        
        '''<remarks/>
        Public Event Get_ComportamientoXmlCompleted As Get_ComportamientoXmlCompletedEventHandler
        
        '''<remarks/>
        Public Event Get_ComportamientoDetXmlCompleted As Get_ComportamientoDetXmlCompletedEventHandler
        
        '''<remarks/>
        Public Event Get_ConexionCompleted As Get_ConexionCompletedEventHandler
        
        '''<remarks/>
        Public Event Get_ConexionBPSCompleted As Get_ConexionBPSCompletedEventHandler
        
        '''<remarks/>
        Public Event Get_BPSConexionWSCompleted As Get_BPSConexionWSCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_Sel_Cuest_Solicitud", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Get_Sel_Cuest_Solicitud(ByVal pin_NumSolicitud As Integer) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("Get_Sel_Cuest_Solicitud", New Object() {pin_NumSolicitud})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Get_Sel_Cuest_SolicitudAsync(ByVal pin_NumSolicitud As Integer)
            Me.Get_Sel_Cuest_SolicitudAsync(pin_NumSolicitud, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Get_Sel_Cuest_SolicitudAsync(ByVal pin_NumSolicitud As Integer, ByVal userState As Object)
            If (Me.Get_Sel_Cuest_SolicitudOperationCompleted Is Nothing) Then
                Me.Get_Sel_Cuest_SolicitudOperationCompleted = AddressOf Me.OnGet_Sel_Cuest_SolicitudOperationCompleted
            End If
            Me.InvokeAsync("Get_Sel_Cuest_Solicitud", New Object() {pin_NumSolicitud}, Me.Get_Sel_Cuest_SolicitudOperationCompleted, userState)
        End Sub
        
        Private Sub OnGet_Sel_Cuest_SolicitudOperationCompleted(ByVal arg As Object)
            If (Not (Me.Get_Sel_Cuest_SolicitudCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Get_Sel_Cuest_SolicitudCompleted(Me, New Get_Sel_Cuest_SolicitudCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_InformacionExterna", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Get_InformacionExterna(ByVal piv_CodTipoDocumento As String, ByVal piv_NumDocumentoIdentidad As String, ByVal xmlParametros As System.Xml.XmlNode) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("Get_InformacionExterna", New Object() {piv_CodTipoDocumento, piv_NumDocumentoIdentidad, xmlParametros})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Get_InformacionExternaAsync(ByVal piv_CodTipoDocumento As String, ByVal piv_NumDocumentoIdentidad As String, ByVal xmlParametros As System.Xml.XmlNode)
            Me.Get_InformacionExternaAsync(piv_CodTipoDocumento, piv_NumDocumentoIdentidad, xmlParametros, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Get_InformacionExternaAsync(ByVal piv_CodTipoDocumento As String, ByVal piv_NumDocumentoIdentidad As String, ByVal xmlParametros As System.Xml.XmlNode, ByVal userState As Object)
            If (Me.Get_InformacionExternaOperationCompleted Is Nothing) Then
                Me.Get_InformacionExternaOperationCompleted = AddressOf Me.OnGet_InformacionExternaOperationCompleted
            End If
            Me.InvokeAsync("Get_InformacionExterna", New Object() {piv_CodTipoDocumento, piv_NumDocumentoIdentidad, xmlParametros}, Me.Get_InformacionExternaOperationCompleted, userState)
        End Sub
        
        Private Sub OnGet_InformacionExternaOperationCompleted(ByVal arg As Object)
            If (Not (Me.Get_InformacionExternaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Get_InformacionExternaCompleted(Me, New Get_InformacionExternaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_CodigoSBS", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Get_CodigoSBS(ByVal piv_CodTipoDocumento As String, ByVal piv_NumDocumentoIdentidad As String) As String
            Dim results() As Object = Me.Invoke("Get_CodigoSBS", New Object() {piv_CodTipoDocumento, piv_NumDocumentoIdentidad})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Get_CodigoSBSAsync(ByVal piv_CodTipoDocumento As String, ByVal piv_NumDocumentoIdentidad As String)
            Me.Get_CodigoSBSAsync(piv_CodTipoDocumento, piv_NumDocumentoIdentidad, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Get_CodigoSBSAsync(ByVal piv_CodTipoDocumento As String, ByVal piv_NumDocumentoIdentidad As String, ByVal userState As Object)
            If (Me.Get_CodigoSBSOperationCompleted Is Nothing) Then
                Me.Get_CodigoSBSOperationCompleted = AddressOf Me.OnGet_CodigoSBSOperationCompleted
            End If
            Me.InvokeAsync("Get_CodigoSBS", New Object() {piv_CodTipoDocumento, piv_NumDocumentoIdentidad}, Me.Get_CodigoSBSOperationCompleted, userState)
        End Sub
        
        Private Sub OnGet_CodigoSBSOperationCompleted(ByVal arg As Object)
            If (Not (Me.Get_CodigoSBSCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Get_CodigoSBSCompleted(Me, New Get_CodigoSBSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_ListadoDeudaRCC", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Get_ListadoDeudaRCC(ByVal piv_DesdePeriodo As String, ByVal piv_FinPeriodo As String, ByVal piv_CodTipoDocumento As String, ByVal piv_NumDocumentoIdentidad As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("Get_ListadoDeudaRCC", New Object() {piv_DesdePeriodo, piv_FinPeriodo, piv_CodTipoDocumento, piv_NumDocumentoIdentidad})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Get_ListadoDeudaRCCAsync(ByVal piv_DesdePeriodo As String, ByVal piv_FinPeriodo As String, ByVal piv_CodTipoDocumento As String, ByVal piv_NumDocumentoIdentidad As String)
            Me.Get_ListadoDeudaRCCAsync(piv_DesdePeriodo, piv_FinPeriodo, piv_CodTipoDocumento, piv_NumDocumentoIdentidad, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Get_ListadoDeudaRCCAsync(ByVal piv_DesdePeriodo As String, ByVal piv_FinPeriodo As String, ByVal piv_CodTipoDocumento As String, ByVal piv_NumDocumentoIdentidad As String, ByVal userState As Object)
            If (Me.Get_ListadoDeudaRCCOperationCompleted Is Nothing) Then
                Me.Get_ListadoDeudaRCCOperationCompleted = AddressOf Me.OnGet_ListadoDeudaRCCOperationCompleted
            End If
            Me.InvokeAsync("Get_ListadoDeudaRCC", New Object() {piv_DesdePeriodo, piv_FinPeriodo, piv_CodTipoDocumento, piv_NumDocumentoIdentidad}, Me.Get_ListadoDeudaRCCOperationCompleted, userState)
        End Sub
        
        Private Sub OnGet_ListadoDeudaRCCOperationCompleted(ByVal arg As Object)
            If (Not (Me.Get_ListadoDeudaRCCCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Get_ListadoDeudaRCCCompleted(Me, New Get_ListadoDeudaRCCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Set_CalcularScoring", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Set_CalcularScoring(ByVal pin_CodCuestionario As Integer, ByVal pin_NumSolicitud As Integer, ByVal piv_CodUsuModifica As String, ByVal xmlInfoCliente As System.Xml.XmlNode, ByVal xmlInfoExterna As System.Xml.XmlNode, ByVal piv_CodTipoDocumento As String, ByVal piv_NumDocumentoIdentidad As String, ByVal piv_CodUnico As String) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("Set_CalcularScoring", New Object() {pin_CodCuestionario, pin_NumSolicitud, piv_CodUsuModifica, xmlInfoCliente, xmlInfoExterna, piv_CodTipoDocumento, piv_NumDocumentoIdentidad, piv_CodUnico})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Set_CalcularScoringAsync(ByVal pin_CodCuestionario As Integer, ByVal pin_NumSolicitud As Integer, ByVal piv_CodUsuModifica As String, ByVal xmlInfoCliente As System.Xml.XmlNode, ByVal xmlInfoExterna As System.Xml.XmlNode, ByVal piv_CodTipoDocumento As String, ByVal piv_NumDocumentoIdentidad As String, ByVal piv_CodUnico As String)
            Me.Set_CalcularScoringAsync(pin_CodCuestionario, pin_NumSolicitud, piv_CodUsuModifica, xmlInfoCliente, xmlInfoExterna, piv_CodTipoDocumento, piv_NumDocumentoIdentidad, piv_CodUnico, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Set_CalcularScoringAsync(ByVal pin_CodCuestionario As Integer, ByVal pin_NumSolicitud As Integer, ByVal piv_CodUsuModifica As String, ByVal xmlInfoCliente As System.Xml.XmlNode, ByVal xmlInfoExterna As System.Xml.XmlNode, ByVal piv_CodTipoDocumento As String, ByVal piv_NumDocumentoIdentidad As String, ByVal piv_CodUnico As String, ByVal userState As Object)
            If (Me.Set_CalcularScoringOperationCompleted Is Nothing) Then
                Me.Set_CalcularScoringOperationCompleted = AddressOf Me.OnSet_CalcularScoringOperationCompleted
            End If
            Me.InvokeAsync("Set_CalcularScoring", New Object() {pin_CodCuestionario, pin_NumSolicitud, piv_CodUsuModifica, xmlInfoCliente, xmlInfoExterna, piv_CodTipoDocumento, piv_NumDocumentoIdentidad, piv_CodUnico}, Me.Set_CalcularScoringOperationCompleted, userState)
        End Sub
        
        Private Sub OnSet_CalcularScoringOperationCompleted(ByVal arg As Object)
            If (Not (Me.Set_CalcularScoringCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Set_CalcularScoringCompleted(Me, New Set_CalcularScoringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_CuestionarioXml", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Get_CuestionarioXml(ByVal TipoCliente As Integer, ByVal TipoPersona As Integer, ByVal NumSolicitud As Integer, ByVal CodSegmento As String) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("Get_CuestionarioXml", New Object() {TipoCliente, TipoPersona, NumSolicitud, CodSegmento})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Get_CuestionarioXmlAsync(ByVal TipoCliente As Integer, ByVal TipoPersona As Integer, ByVal NumSolicitud As Integer, ByVal CodSegmento As String)
            Me.Get_CuestionarioXmlAsync(TipoCliente, TipoPersona, NumSolicitud, CodSegmento, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Get_CuestionarioXmlAsync(ByVal TipoCliente As Integer, ByVal TipoPersona As Integer, ByVal NumSolicitud As Integer, ByVal CodSegmento As String, ByVal userState As Object)
            If (Me.Get_CuestionarioXmlOperationCompleted Is Nothing) Then
                Me.Get_CuestionarioXmlOperationCompleted = AddressOf Me.OnGet_CuestionarioXmlOperationCompleted
            End If
            Me.InvokeAsync("Get_CuestionarioXml", New Object() {TipoCliente, TipoPersona, NumSolicitud, CodSegmento}, Me.Get_CuestionarioXmlOperationCompleted, userState)
        End Sub
        
        Private Sub OnGet_CuestionarioXmlOperationCompleted(ByVal arg As Object)
            If (Not (Me.Get_CuestionarioXmlCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Get_CuestionarioXmlCompleted(Me, New Get_CuestionarioXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Set_CuestionarioSolicitud", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Set_CuestionarioSolicitud(ByVal CodCuestionario As Integer, ByVal NumSolicitud As Integer, ByVal CodUsuCrea As String, ByVal XMLPregunta As String) As Integer
            Dim results() As Object = Me.Invoke("Set_CuestionarioSolicitud", New Object() {CodCuestionario, NumSolicitud, CodUsuCrea, XMLPregunta})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Set_CuestionarioSolicitudAsync(ByVal CodCuestionario As Integer, ByVal NumSolicitud As Integer, ByVal CodUsuCrea As String, ByVal XMLPregunta As String)
            Me.Set_CuestionarioSolicitudAsync(CodCuestionario, NumSolicitud, CodUsuCrea, XMLPregunta, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Set_CuestionarioSolicitudAsync(ByVal CodCuestionario As Integer, ByVal NumSolicitud As Integer, ByVal CodUsuCrea As String, ByVal XMLPregunta As String, ByVal userState As Object)
            If (Me.Set_CuestionarioSolicitudOperationCompleted Is Nothing) Then
                Me.Set_CuestionarioSolicitudOperationCompleted = AddressOf Me.OnSet_CuestionarioSolicitudOperationCompleted
            End If
            Me.InvokeAsync("Set_CuestionarioSolicitud", New Object() {CodCuestionario, NumSolicitud, CodUsuCrea, XMLPregunta}, Me.Set_CuestionarioSolicitudOperationCompleted, userState)
        End Sub
        
        Private Sub OnSet_CuestionarioSolicitudOperationCompleted(ByVal arg As Object)
            If (Not (Me.Set_CuestionarioSolicitudCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Set_CuestionarioSolicitudCompleted(Me, New Set_CuestionarioSolicitudCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_Lst_Sist_Model_Area_Valor", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Get_Lst_Sist_Model_Area_Valor() As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("Get_Lst_Sist_Model_Area_Valor", New Object(-1) {})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Get_Lst_Sist_Model_Area_ValorAsync()
            Me.Get_Lst_Sist_Model_Area_ValorAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Get_Lst_Sist_Model_Area_ValorAsync(ByVal userState As Object)
            If (Me.Get_Lst_Sist_Model_Area_ValorOperationCompleted Is Nothing) Then
                Me.Get_Lst_Sist_Model_Area_ValorOperationCompleted = AddressOf Me.OnGet_Lst_Sist_Model_Area_ValorOperationCompleted
            End If
            Me.InvokeAsync("Get_Lst_Sist_Model_Area_Valor", New Object(-1) {}, Me.Get_Lst_Sist_Model_Area_ValorOperationCompleted, userState)
        End Sub
        
        Private Sub OnGet_Lst_Sist_Model_Area_ValorOperationCompleted(ByVal arg As Object)
            If (Not (Me.Get_Lst_Sist_Model_Area_ValorCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Get_Lst_Sist_Model_Area_ValorCompleted(Me, New Get_Lst_Sist_Model_Area_ValorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_List_Cuest_SolicitudDetalle", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Get_List_Cuest_SolicitudDetalle(ByVal CodCuestionario As Integer, ByVal NumSolicitud As Integer, ByVal FlgEstado As String, ByVal CodAreaValoracion As Integer, ByVal Flag As Integer) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("Get_List_Cuest_SolicitudDetalle", New Object() {CodCuestionario, NumSolicitud, FlgEstado, CodAreaValoracion, Flag})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Get_List_Cuest_SolicitudDetalleAsync(ByVal CodCuestionario As Integer, ByVal NumSolicitud As Integer, ByVal FlgEstado As String, ByVal CodAreaValoracion As Integer, ByVal Flag As Integer)
            Me.Get_List_Cuest_SolicitudDetalleAsync(CodCuestionario, NumSolicitud, FlgEstado, CodAreaValoracion, Flag, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Get_List_Cuest_SolicitudDetalleAsync(ByVal CodCuestionario As Integer, ByVal NumSolicitud As Integer, ByVal FlgEstado As String, ByVal CodAreaValoracion As Integer, ByVal Flag As Integer, ByVal userState As Object)
            If (Me.Get_List_Cuest_SolicitudDetalleOperationCompleted Is Nothing) Then
                Me.Get_List_Cuest_SolicitudDetalleOperationCompleted = AddressOf Me.OnGet_List_Cuest_SolicitudDetalleOperationCompleted
            End If
            Me.InvokeAsync("Get_List_Cuest_SolicitudDetalle", New Object() {CodCuestionario, NumSolicitud, FlgEstado, CodAreaValoracion, Flag}, Me.Get_List_Cuest_SolicitudDetalleOperationCompleted, userState)
        End Sub
        
        Private Sub OnGet_List_Cuest_SolicitudDetalleOperationCompleted(ByVal arg As Object)
            If (Not (Me.Get_List_Cuest_SolicitudDetalleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Get_List_Cuest_SolicitudDetalleCompleted(Me, New Get_List_Cuest_SolicitudDetalleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_ComportamientoXml", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Get_ComportamientoXml(ByVal Flag As Integer, ByVal CodUnico As String) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("Get_ComportamientoXml", New Object() {Flag, CodUnico})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Get_ComportamientoXmlAsync(ByVal Flag As Integer, ByVal CodUnico As String)
            Me.Get_ComportamientoXmlAsync(Flag, CodUnico, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Get_ComportamientoXmlAsync(ByVal Flag As Integer, ByVal CodUnico As String, ByVal userState As Object)
            If (Me.Get_ComportamientoXmlOperationCompleted Is Nothing) Then
                Me.Get_ComportamientoXmlOperationCompleted = AddressOf Me.OnGet_ComportamientoXmlOperationCompleted
            End If
            Me.InvokeAsync("Get_ComportamientoXml", New Object() {Flag, CodUnico}, Me.Get_ComportamientoXmlOperationCompleted, userState)
        End Sub
        
        Private Sub OnGet_ComportamientoXmlOperationCompleted(ByVal arg As Object)
            If (Not (Me.Get_ComportamientoXmlCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Get_ComportamientoXmlCompleted(Me, New Get_ComportamientoXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_ComportamientoDetXml", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Get_ComportamientoDetXml(ByVal CodUnico As String, ByVal Periodo As String) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("Get_ComportamientoDetXml", New Object() {CodUnico, Periodo})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Get_ComportamientoDetXmlAsync(ByVal CodUnico As String, ByVal Periodo As String)
            Me.Get_ComportamientoDetXmlAsync(CodUnico, Periodo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Get_ComportamientoDetXmlAsync(ByVal CodUnico As String, ByVal Periodo As String, ByVal userState As Object)
            If (Me.Get_ComportamientoDetXmlOperationCompleted Is Nothing) Then
                Me.Get_ComportamientoDetXmlOperationCompleted = AddressOf Me.OnGet_ComportamientoDetXmlOperationCompleted
            End If
            Me.InvokeAsync("Get_ComportamientoDetXml", New Object() {CodUnico, Periodo}, Me.Get_ComportamientoDetXmlOperationCompleted, userState)
        End Sub
        
        Private Sub OnGet_ComportamientoDetXmlOperationCompleted(ByVal arg As Object)
            If (Not (Me.Get_ComportamientoDetXmlCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Get_ComportamientoDetXmlCompleted(Me, New Get_ComportamientoDetXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_Conexion", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Get_Conexion(ByVal pstrAmbiente As Integer, ByVal pstrUsuario As String, ByVal pstrContrasenia As String, ByVal pstrDSN As String, ByVal pstrHost As String, ByVal pstrPuerto As String) As String
            Dim results() As Object = Me.Invoke("Get_Conexion", New Object() {pstrAmbiente, pstrUsuario, pstrContrasenia, pstrDSN, pstrHost, pstrPuerto})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Get_ConexionAsync(ByVal pstrAmbiente As Integer, ByVal pstrUsuario As String, ByVal pstrContrasenia As String, ByVal pstrDSN As String, ByVal pstrHost As String, ByVal pstrPuerto As String)
            Me.Get_ConexionAsync(pstrAmbiente, pstrUsuario, pstrContrasenia, pstrDSN, pstrHost, pstrPuerto, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Get_ConexionAsync(ByVal pstrAmbiente As Integer, ByVal pstrUsuario As String, ByVal pstrContrasenia As String, ByVal pstrDSN As String, ByVal pstrHost As String, ByVal pstrPuerto As String, ByVal userState As Object)
            If (Me.Get_ConexionOperationCompleted Is Nothing) Then
                Me.Get_ConexionOperationCompleted = AddressOf Me.OnGet_ConexionOperationCompleted
            End If
            Me.InvokeAsync("Get_Conexion", New Object() {pstrAmbiente, pstrUsuario, pstrContrasenia, pstrDSN, pstrHost, pstrPuerto}, Me.Get_ConexionOperationCompleted, userState)
        End Sub
        
        Private Sub OnGet_ConexionOperationCompleted(ByVal arg As Object)
            If (Not (Me.Get_ConexionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Get_ConexionCompleted(Me, New Get_ConexionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_ConexionBPS", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Get_ConexionBPS(ByVal pstrAmbiente As Integer, ByVal pstrLlave As String) As String
            Dim results() As Object = Me.Invoke("Get_ConexionBPS", New Object() {pstrAmbiente, pstrLlave})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Get_ConexionBPSAsync(ByVal pstrAmbiente As Integer, ByVal pstrLlave As String)
            Me.Get_ConexionBPSAsync(pstrAmbiente, pstrLlave, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Get_ConexionBPSAsync(ByVal pstrAmbiente As Integer, ByVal pstrLlave As String, ByVal userState As Object)
            If (Me.Get_ConexionBPSOperationCompleted Is Nothing) Then
                Me.Get_ConexionBPSOperationCompleted = AddressOf Me.OnGet_ConexionBPSOperationCompleted
            End If
            Me.InvokeAsync("Get_ConexionBPS", New Object() {pstrAmbiente, pstrLlave}, Me.Get_ConexionBPSOperationCompleted, userState)
        End Sub
        
        Private Sub OnGet_ConexionBPSOperationCompleted(ByVal arg As Object)
            If (Not (Me.Get_ConexionBPSCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Get_ConexionBPSCompleted(Me, New Get_ConexionBPSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_BPSConexionWS", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Get_BPSConexionWS(ByVal pstrAmbiente As String, ByVal pstrLlave As String) As String
            Dim results() As Object = Me.Invoke("Get_BPSConexionWS", New Object() {pstrAmbiente, pstrLlave})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Get_BPSConexionWSAsync(ByVal pstrAmbiente As String, ByVal pstrLlave As String)
            Me.Get_BPSConexionWSAsync(pstrAmbiente, pstrLlave, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Get_BPSConexionWSAsync(ByVal pstrAmbiente As String, ByVal pstrLlave As String, ByVal userState As Object)
            If (Me.Get_BPSConexionWSOperationCompleted Is Nothing) Then
                Me.Get_BPSConexionWSOperationCompleted = AddressOf Me.OnGet_BPSConexionWSOperationCompleted
            End If
            Me.InvokeAsync("Get_BPSConexionWS", New Object() {pstrAmbiente, pstrLlave}, Me.Get_BPSConexionWSOperationCompleted, userState)
        End Sub
        
        Private Sub OnGet_BPSConexionWSOperationCompleted(ByVal arg As Object)
            If (Not (Me.Get_BPSConexionWSCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Get_BPSConexionWSCompleted(Me, New Get_BPSConexionWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub Get_Sel_Cuest_SolicitudCompletedEventHandler(ByVal sender As Object, ByVal e As Get_Sel_Cuest_SolicitudCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Get_Sel_Cuest_SolicitudCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Xml.XmlNode
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Xml.XmlNode)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub Get_InformacionExternaCompletedEventHandler(ByVal sender As Object, ByVal e As Get_InformacionExternaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Get_InformacionExternaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Xml.XmlNode
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Xml.XmlNode)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub Get_CodigoSBSCompletedEventHandler(ByVal sender As Object, ByVal e As Get_CodigoSBSCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Get_CodigoSBSCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub Get_ListadoDeudaRCCCompletedEventHandler(ByVal sender As Object, ByVal e As Get_ListadoDeudaRCCCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Get_ListadoDeudaRCCCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub Set_CalcularScoringCompletedEventHandler(ByVal sender As Object, ByVal e As Set_CalcularScoringCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Set_CalcularScoringCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Xml.XmlNode
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Xml.XmlNode)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub Get_CuestionarioXmlCompletedEventHandler(ByVal sender As Object, ByVal e As Get_CuestionarioXmlCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Get_CuestionarioXmlCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Xml.XmlNode
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Xml.XmlNode)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub Set_CuestionarioSolicitudCompletedEventHandler(ByVal sender As Object, ByVal e As Set_CuestionarioSolicitudCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Set_CuestionarioSolicitudCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub Get_Lst_Sist_Model_Area_ValorCompletedEventHandler(ByVal sender As Object, ByVal e As Get_Lst_Sist_Model_Area_ValorCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Get_Lst_Sist_Model_Area_ValorCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Xml.XmlNode
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Xml.XmlNode)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub Get_List_Cuest_SolicitudDetalleCompletedEventHandler(ByVal sender As Object, ByVal e As Get_List_Cuest_SolicitudDetalleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Get_List_Cuest_SolicitudDetalleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Xml.XmlNode
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Xml.XmlNode)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub Get_ComportamientoXmlCompletedEventHandler(ByVal sender As Object, ByVal e As Get_ComportamientoXmlCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Get_ComportamientoXmlCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Xml.XmlNode
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Xml.XmlNode)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub Get_ComportamientoDetXmlCompletedEventHandler(ByVal sender As Object, ByVal e As Get_ComportamientoDetXmlCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Get_ComportamientoDetXmlCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Xml.XmlNode
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Xml.XmlNode)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub Get_ConexionCompletedEventHandler(ByVal sender As Object, ByVal e As Get_ConexionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Get_ConexionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub Get_ConexionBPSCompletedEventHandler(ByVal sender As Object, ByVal e As Get_ConexionBPSCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Get_ConexionBPSCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub Get_BPSConexionWSCompletedEventHandler(ByVal sender As Object, ByVal e As Get_BPSConexionWSCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Get_BPSConexionWSCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
