'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.3634
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace CEF.WebUI

    '''<summary>
    '''Clase Portal.
    '''</summary>
    '''<remarks>
    '''Clase generada automáticamente.
    '''</remarks>
    Partial Public Class Portal

        '''<summary>
        '''Control Form1.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''Control imgBanner.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents imgBanner As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''Control tdBanner.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents tdBanner As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''Control lblUsuario.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents lblUsuario As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Control lblPerfil.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents lblPerfil As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Control lbtnSalir.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents lbtnSalir As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''Control Menu1.
        '''</summary>
        '''<remarks>
        '''Campo generado automáticamente.
        '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        '''</remarks>
        Protected WithEvents Menu1 As Global.CEF.WebIU.Menu
    End Class
End Namespace
